# Build pipeline for Ubuntu and Windows

trigger:
- main
jobs:

- job: 'Ubuntu'
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.5'
      addToPath: true
  - task: CmdLine@2
    inputs:
      script: |
        python -m pip install --upgrade pip
        python -m pip install matplotlib
        python -m pip install PyQt5
        python -m pip install PyInstaller
  - task: CmdLine@2
    inputs:
      script: 'python -m PyInstaller ChronoPlotter.py --onefile'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)/s/dist/ChronoPlotter'
      artifact: 'build-ubuntu'
      publishLocation: 'pipeline'

- job: 'Windows'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.5'
      addToPath: true
  - task: CmdLine@2
    inputs:
      script: |
        python -m pip install --upgrade pip
        python -m pip install matplotlib
        python -m pip install PyQt5
        python -m pip install PyInstaller
  - task: CmdLine@2
    inputs:
      script: 'python -m PyInstaller ChronoPlotter.py --onefile -w'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)\s\dist\ChronoPlotter.exe'
      artifact: 'build-win'
      publishLocation: 'pipeline'